runner:
  image:
    repository: ghcr.io/yitsushi/tf-runner
    tag: build-daa7a3c852613f9b-1702999007
  serviceAccount:
    allowedNamespaces:
      - flux-system
      - terraform

branchPlanner:
  enabled: true
